name: Main branch build, test, publish

on:
  push:
    branches: [ main ]


permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: 'sbt'
    - name: Validate code formatting
      run: sbt scalafmtCheckAll
    - name: Run tests
      run: sbt test
    - name: Publish data objects to Maven Package
      run: sbt dataObjects/publish
      env:
        GITHUB_TOKEN: ${{ secrets.POC_PACKAGE_TOKEN }}
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: Semer7
        password: ${{ secrets.POC_PACKAGE_TOKEN }}
    - name: Publish to GitHub Docker Package
      run: sbt docker:publish

